/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/rescue-tracking`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigation` | `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved-maps` | `/saved-maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/share-location` | `/share-location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weather-radar` | `/weather-radar`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/rescue-tracking`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigation` | `/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/saved-maps` | `/saved-maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/share-location` | `/share-location`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/weather-radar` | `/weather-radar`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/rescue-tracking${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigation${`?${string}` | `#${string}` | ''}` | `/navigation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/saved-maps${`?${string}` | `#${string}` | ''}` | `/saved-maps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/share-location${`?${string}` | `#${string}` | ''}` | `/share-location${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/weather-radar${`?${string}` | `#${string}` | ''}` | `/weather-radar${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/rescue-tracking`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigation` | `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved-maps` | `/saved-maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/share-location` | `/share-location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weather-radar` | `/weather-radar`; params?: Router.UnknownInputParams; };
    }
  }
}
